# -*- coding: utf-8 -*-
# ======================================================================================
# Copyright (©) 2015-2023 LCS - Laboratoire Catalyse et Spectrochimie, Caen, France.
# CeCILL-B FREE SOFTWARE LICENSE AGREEMENT
# See full LICENSE agreement in the root directory.
# ======================================================================================
#
#
#    ###################################################################################
#    #           DO NOT MODIFY THIS FILE BECAUSE IT IS CREATED AUTOMATICALLY.          #
#    #   ANY MODIFICATION OF THIS FILE WILL BE CANCELLED AFTER THE COMMIT IN GITHUB.   #
#    ###################################################################################
#
#
# flake8: noqa
"""
SpectroChemPy API.
"""
import sys

from spectrochempy.utils.lazy_imports import LazyImporter

_api_methods = {
    "coverages_vs_time": "spectrochempy.analysis.cantera_utilities",
    "concentrations_vs_time": "spectrochempy.analysis.cantera_utilities",
    "modify_rate": "spectrochempy.analysis.cantera_utilities",
    "modify_surface_kinetics": "spectrochempy.analysis.cantera_utilities",
    "fit_to_concentrations": "spectrochempy.analysis.cantera_utilities",
    "PFR": "spectrochempy.analysis.cantera_utilities",
    "EFA": "spectrochempy.analysis.efa",
    "Fit": "spectrochempy.analysis.fitting",
    "FitParameters": "spectrochempy.analysis.fitting",
    "ParameterScript": "spectrochempy.analysis.fitting",
    "IRIS": "spectrochempy.analysis.iris",
    "kern": "spectrochempy.analysis.iris",
    "CurveFit": "spectrochempy.analysis.lstsq",
    "LSTSQ": "spectrochempy.analysis.lstsq",
    "NNLS": "spectrochempy.analysis.lstsq",
    "MCRALS": "spectrochempy.analysis.mcrals",
    "polynomialbaseline": "spectrochempy.analysis.models",
    "gaussianmodel": "spectrochempy.analysis.models",
    "lorentzianmodel": "spectrochempy.analysis.models",
    "voigtmodel": "spectrochempy.analysis.models",
    "asymmetricvoigtmodel": "spectrochempy.analysis.models",
    "sigmoidmodel": "spectrochempy.analysis.models",
    "NNMF": "spectrochempy.analysis.nnmf",
    "PCA": "spectrochempy.analysis.pca",
    "find_peaks": "spectrochempy.analysis.peakfinding",
    "SIMPLISMA": "spectrochempy.analysis.simplisma",
    "SVD": "spectrochempy.analysis.svd",
    "NO_DISPLAY": "spectrochempy.application",
    "app": "spectrochempy.application",
    "info_": "spectrochempy.application",
    "debug_": "spectrochempy.application",
    "warning_": "spectrochempy.application",
    "error_": "spectrochempy.application",
    "save_dialog": "spectrochempy.application",
    "open_dialog": "spectrochempy.application",
    "preferences": "spectrochempy.application",
    "set_loglevel": "spectrochempy.application",
    "get_loglevel": "spectrochempy.application",
    "DATADIR": "spectrochempy.application",
    "load": "spectrochempy.core.dataset.arraymixins.ndio",
    "abs": "spectrochempy.core.dataset.arraymixins.ndmath",
    "absolute": "spectrochempy.core.dataset.arraymixins.ndmath",
    "all": "spectrochempy.core.dataset.arraymixins.ndmath",
    "amax": "spectrochempy.core.dataset.arraymixins.ndmath",
    "amin": "spectrochempy.core.dataset.arraymixins.ndmath",
    "any": "spectrochempy.core.dataset.arraymixins.ndmath",
    "arange": "spectrochempy.core.dataset.arraymixins.ndmath",
    "argmax": "spectrochempy.core.dataset.arraymixins.ndmath",
    "argmin": "spectrochempy.core.dataset.arraymixins.ndmath",
    "around": "spectrochempy.core.dataset.arraymixins.ndmath",
    "average": "spectrochempy.core.dataset.arraymixins.ndmath",
    "clip": "spectrochempy.core.dataset.arraymixins.ndmath",
    "conj": "spectrochempy.core.dataset.arraymixins.ndmath",
    "conjugate": "spectrochempy.core.dataset.arraymixins.ndmath",
    "coordmax": "spectrochempy.core.dataset.arraymixins.ndmath",
    "coordmin": "spectrochempy.core.dataset.arraymixins.ndmath",
    "cumsum": "spectrochempy.core.dataset.arraymixins.ndmath",
    "diag": "spectrochempy.core.dataset.arraymixins.ndmath",
    "diagonal": "spectrochempy.core.dataset.arraymixins.ndmath",
    "empty": "spectrochempy.core.dataset.arraymixins.ndmath",
    "empty_like": "spectrochempy.core.dataset.arraymixins.ndmath",
    "eye": "spectrochempy.core.dataset.arraymixins.ndmath",
    "fromfunction": "spectrochempy.core.dataset.arraymixins.ndmath",
    "fromiter": "spectrochempy.core.dataset.arraymixins.ndmath",
    "full": "spectrochempy.core.dataset.arraymixins.ndmath",
    "full_like": "spectrochempy.core.dataset.arraymixins.ndmath",
    "geomspace": "spectrochempy.core.dataset.arraymixins.ndmath",
    "identity": "spectrochempy.core.dataset.arraymixins.ndmath",
    "linspace": "spectrochempy.core.dataset.arraymixins.ndmath",
    "logspace": "spectrochempy.core.dataset.arraymixins.ndmath",
    "max": "spectrochempy.core.dataset.arraymixins.ndmath",
    "mean": "spectrochempy.core.dataset.arraymixins.ndmath",
    "min": "spectrochempy.core.dataset.arraymixins.ndmath",
    "ones": "spectrochempy.core.dataset.arraymixins.ndmath",
    "ones_like": "spectrochempy.core.dataset.arraymixins.ndmath",
    "pipe": "spectrochempy.core.dataset.arraymixins.ndmath",
    "ptp": "spectrochempy.core.dataset.arraymixins.ndmath",
    "random": "spectrochempy.core.dataset.arraymixins.ndmath",
    "round": "spectrochempy.core.dataset.arraymixins.ndmath",
    "round_": "spectrochempy.core.dataset.arraymixins.ndmath",
    "std": "spectrochempy.core.dataset.arraymixins.ndmath",
    "sum": "spectrochempy.core.dataset.arraymixins.ndmath",
    "var": "spectrochempy.core.dataset.arraymixins.ndmath",
    "zeros": "spectrochempy.core.dataset.arraymixins.ndmath",
    "zeros_like": "spectrochempy.core.dataset.arraymixins.ndmath",
    "plot": "spectrochempy.core.dataset.arraymixins.ndplot",
    "dot": "spectrochempy.core.dataset.arraymixins.npy",
    "Meta": "spectrochempy.core.dataset.baseobjects.meta",
    "Coord": "spectrochempy.core.dataset.coord",
    "LinearCoord": "spectrochempy.core.dataset.coord",
    "CoordSet": "spectrochempy.core.dataset.coordset",
    "NDDataset": "spectrochempy.core.dataset.nddataset",
    "sort": "spectrochempy.core.dataset.nddataset",
    "copy": "spectrochempy.core.dataset.nddataset",
    "squeeze": "spectrochempy.core.dataset.nddataset",
    "swapdims": "spectrochempy.core.dataset.nddataset",
    "transpose": "spectrochempy.core.dataset.nddataset",
    "to_array": "spectrochempy.core.dataset.nddataset",
    "to_xarray": "spectrochempy.core.dataset.nddataset",
    "take": "spectrochempy.core.dataset.nddataset",
    "set_complex": "spectrochempy.core.dataset.nddataset",
    "set_quaternion": "spectrochempy.core.dataset.nddataset",
    "set_hypercomplex": "spectrochempy.core.dataset.nddataset",
    "component": "spectrochempy.core.dataset.nddataset",
    "to": "spectrochempy.core.dataset.nddataset",
    "to_base_units": "spectrochempy.core.dataset.nddataset",
    "to_reduced_units": "spectrochempy.core.dataset.nddataset",
    "ito": "spectrochempy.core.dataset.nddataset",
    "ito_base_units": "spectrochempy.core.dataset.nddataset",
    "ito_reduced_units": "spectrochempy.core.dataset.nddataset",
    "is_units_compatible": "spectrochempy.core.dataset.nddataset",
    "remove_masks": "spectrochempy.core.dataset.nddataset",
    "multiplot": "spectrochempy.core.plotters.multiplot",
    "multiplot_map": "spectrochempy.core.plotters.multiplot",
    "multiplot_stack": "spectrochempy.core.plotters.multiplot",
    "multiplot_image": "spectrochempy.core.plotters.multiplot",
    "multiplot_lines": "spectrochempy.core.plotters.multiplot",
    "multiplot_scatter": "spectrochempy.core.plotters.multiplot",
    "multiplot_with_transposed": "spectrochempy.core.plotters.multiplot",
    "plot_with_transposed": "spectrochempy.core.plotters.multiplot",
    "plot_1D": "spectrochempy.core.plotters.plot1d",
    "plot_pen": "spectrochempy.core.plotters.plot1d",
    "plot_scatter": "spectrochempy.core.plotters.plot1d",
    "plot_bar": "spectrochempy.core.plotters.plot1d",
    "plot_multiple": "spectrochempy.core.plotters.plot1d",
    "plot_scatter_pen": "spectrochempy.core.plotters.plot1d",
    "plot_2D": "spectrochempy.core.plotters.plot2d",
    "plot_map": "spectrochempy.core.plotters.plot2d",
    "plot_stack": "spectrochempy.core.plotters.plot2d",
    "plot_image": "spectrochempy.core.plotters.plot2d",
    "plot_3D": "spectrochempy.core.plotters.plot3d",
    "plot_surface": "spectrochempy.core.plotters.plot3d",
    "plot_waterfall": "spectrochempy.core.plotters.plot3d",
    "align": "spectrochempy.core.processors.align",
    "em": "spectrochempy.core.processors.apodization",
    "gm": "spectrochempy.core.processors.apodization",
    "sp": "spectrochempy.core.processors.apodization",
    "sine": "spectrochempy.core.processors.apodization",
    "sinm": "spectrochempy.core.processors.apodization",
    "qsin": "spectrochempy.core.processors.apodization",
    "general_hamming": "spectrochempy.core.processors.apodization",
    "hamming": "spectrochempy.core.processors.apodization",
    "hann": "spectrochempy.core.processors.apodization",
    "triang": "spectrochempy.core.processors.apodization",
    "bartlett": "spectrochempy.core.processors.apodization",
    "blackmanharris": "spectrochempy.core.processors.apodization",
    "autosub": "spectrochempy.core.processors.autosub",
    "BaselineCorrection": "spectrochempy.core.processors.baseline",
    "ab": "spectrochempy.core.processors.baseline",
    "abc": "spectrochempy.core.processors.baseline",
    "dc": "spectrochempy.core.processors.baseline",
    "basc": "spectrochempy.core.processors.baseline",
    "concatenate": "spectrochempy.core.processors.concatenate",
    "stack": "spectrochempy.core.processors.concatenate",
    "fft": "spectrochempy.core.processors.fft",
    "ifft": "spectrochempy.core.processors.fft",
    "mc": "spectrochempy.core.processors.fft",
    "ps": "spectrochempy.core.processors.fft",
    "ht": "spectrochempy.core.processors.fft",
    "savgol_filter": "spectrochempy.core.processors.filter",
    "detrend": "spectrochempy.core.processors.filter",
    "smooth": "spectrochempy.core.processors.filter",
    "simps": "spectrochempy.core.processors.integrate",
    "trapz": "spectrochempy.core.processors.integrate",
    "simpson": "spectrochempy.core.processors.integrate",
    "trapezoid": "spectrochempy.core.processors.integrate",
    "interpolate": "spectrochempy.core.processors.interpolate",
    "pk": "spectrochempy.core.processors.phasing",
    "pk_exp": "spectrochempy.core.processors.phasing",
    "rs": "spectrochempy.core.processors.shift",
    "ls": "spectrochempy.core.processors.shift",
    "roll": "spectrochempy.core.processors.shift",
    "cs": "spectrochempy.core.processors.shift",
    "fsh": "spectrochempy.core.processors.shift",
    "fsh2": "spectrochempy.core.processors.shift",
    "zf_auto": "spectrochempy.core.processors.zero_filling",
    "zf_double": "spectrochempy.core.processors.zero_filling",
    "zf_size": "spectrochempy.core.processors.zero_filling",
    "zf": "spectrochempy.core.processors.zero_filling",
    "Project": "spectrochempy.core.project.project",
    "download_iris": "spectrochempy.core.readers.download",
    "download_nist_ir": "spectrochempy.core.readers.download",
    "read": "spectrochempy.core.readers.importer",
    "read_dir": "spectrochempy.core.readers.importer",
    "read_remote": "spectrochempy.core.readers.importer",
    "read_carroucell": "spectrochempy.core.readers.read_carroucell",
    "read_csv": "spectrochempy.core.readers.read_csv",
    "read_jcamp": "spectrochempy.core.readers.read_jcamp",
    "read_jdx": "spectrochempy.core.readers.read_jcamp",
    "read_dx": "spectrochempy.core.readers.read_jcamp",
    "read_labspec": "spectrochempy.core.readers.read_labspec",
    "read_matlab": "spectrochempy.core.readers.read_matlab",
    "read_mat": "spectrochempy.core.readers.read_matlab",
    "read_omnic": "spectrochempy.core.readers.read_omnic",
    "read_spg": "spectrochempy.core.readers.read_omnic",
    "read_spa": "spectrochempy.core.readers.read_omnic",
    "read_srs": "spectrochempy.core.readers.read_omnic",
    "read_opus": "spectrochempy.core.readers.read_opus",
    "read_quadera": "spectrochempy.core.readers.read_quadera",
    "read_soc": "spectrochempy.core.readers.read_soc",
    "read_ddr": "spectrochempy.core.readers.read_soc",
    "read_sdr": "spectrochempy.core.readers.read_soc",
    "read_hdr": "spectrochempy.core.readers.read_soc",
    "read_spc": "spectrochempy.core.readers.read_spc",
    "read_topspin": "spectrochempy.core.readers.read_topspin",
    "read_bruker_nmr": "spectrochempy.core.readers.read_topspin",
    "read_zip": "spectrochempy.core.readers.read_zip",
    "Script": "spectrochempy.core.script",
    "run_script": "spectrochempy.core.script",
    "run_all_scripts": "spectrochempy.core.script",
    "Unit": "spectrochempy.core.units",
    "Quantity": "spectrochempy.core.units",
    "ur": "spectrochempy.core.units",
    "set_nmr_context": "spectrochempy.core.units",
    "DimensionalityError": "spectrochempy.core.units",
    "write": "spectrochempy.core.writers.exporter",
    "write_csv": "spectrochempy.core.writers.write_csv",
    "write_excel": "spectrochempy.core.writers.write_excel",
    "write_xls": "spectrochempy.core.writers.write_excel",
    "write_jcamp": "spectrochempy.core.writers.write_jcamp",
    "write_jdx": "spectrochempy.core.writers.write_jcamp",
    "write_matlab": "spectrochempy.core.writers.write_matlab",
    "write_mat": "spectrochempy.core.writers.write_matlab",
    "MASKED": "spectrochempy.utils.constants",
    "NOMASK": "spectrochempy.utils.constants",
    "DEFAULT_DIM_NAME": "spectrochempy.utils.constants",
    "make_new_object": "spectrochempy.utils.misc",
    "pathclean": "spectrochempy.utils.paths",
    "show": "spectrochempy.utils.plots",
    "close_all_figures": "spectrochempy.utils.plots",
    "print_versions": "spectrochempy.utils.print_versions",
    "BaselineCorrector": "spectrochempy.widgets.baselinecorrector",
    "FileSelector": "spectrochempy.widgets.fileselector",
}


sys.modules[__name__] = LazyImporter(__name__, globals()["__file__"], _api_methods)


# --------------------------------------------------------------------------------------
# Search for NDDataset method which can be used as API methods
# --------------------------------------------------------------------------------------
def __getattr__(name):
    from spectrochempy.core.dataset.nddataset import NDDataset

    if hasattr(NDDataset, name):
        return getattr(NDDataset, name)
    raise AttributeError
