_importer_methods = {
	'_read_dir': 'spectrochempy.core.readers.importer',
	 '_read_scp': 'spectrochempy.core.readers.importer',
	 '_read_': 'spectrochempy.core.readers.importer',
	 '_read_remote': 'spectrochempy.core.readers.importer',
	 '_read_jdx': 'spectrochempy.core.readers.read_jcamp',
	 '_read_dx': 'spectrochempy.core.readers.read_jcamp',
	 '_read_spg': 'spectrochempy.core.readers.read_omnic',
	 '_read_spa': 'spectrochempy.core.readers.read_omnic',
	 '_read_srs': 'spectrochempy.core.readers.read_omnic',
	 '_read_carroucell': 'spectrochempy.core.readers.read_carroucell',
	 '_read_csv': 'spectrochempy.core.readers.read_csv',
	 '_read_txt': 'spectrochempy.core.readers.read_labspec',
	 '_read_mat': 'spectrochempy.core.readers.read_matlab',
	 '_read_dso': 'spectrochempy.core.readers.read_matlab',
	 '_read_opus': 'spectrochempy.core.readers.read_opus',
	 '_read_asc': 'spectrochempy.core.readers.read_quadera',
	 '_read_ddr': 'spectrochempy.core.readers.read_soc',
	 '_read_hdr': 'spectrochempy.core.readers.read_soc',
	 '_read_sdr': 'spectrochempy.core.readers.read_soc',
	 '_read_spc': 'spectrochempy.core.readers.read_spc',
	 '_read_topspin': 'spectrochempy.core.readers.read_topspin',
	 '_read_wdf': 'spectrochempy.core.readers.read_wire',
	 '_read_zip': 'spectrochempy.core.readers.read_zip',
	 '_read_fake': 'test_importer',
	 '_read_fk': 'test_importer'
}