name: Create release

on:
  workflow_dispatch:
    inputs:
      versionString:
        description: 'version  (e.g. 0.4.2)'
        required: true
jobs:

  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create branch
        run: git checkout -b release/v${{ github.event.inputs.versionString }}
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Update version in CHANGELOG, .zenodo.json and CITATION.cff
        run: |
          python scripts/create_requirements.py
      - name: Update version in CHANGELOG, .zenodo.json and CITATION.cff
        run: |
          python scripts/update_version.py ${{ github.event.inputs.versionString }}
      - name: Commit CHANGELOG.md, .zenodo.json and CITATION.cff updated
        id: make-commit
        run: |
          git add CHANGELOG.md
          git add .zenodo.json
          git add CITATION.cff
          git commit --message "Prepare release ${{ github.event.inputs.versionString }}"
          echo "::set-output name=commit::$(git rev-parse HEAD)"
      - name: Push new branch
        run: git push origin release/v${{ github.event.inputs.versionString }}
      - name: Create pull request into master
        uses: thomaseizinger/create-pull-request@1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: release/v${{ github.event.inputs.versionString }}
          base: master
          title: v${{ github.event.inputs.versionString }} into master
          body: |
            This PR was created in response workflow running.
            I've updated the version string and code commit: ${{ steps.make-commit.outputs.commit }}.
      - name: Prepare next changelog
        run: |
          python scripts/update_version.py unreleased
